vich_uploader:
    db_driver: orm
    mappings:
        media:
            uri_prefix: '/upload/media'
            upload_destination: '%kernel.project_dir%/public/upload/media'
        entity_with_image:
            uri_prefix: '/upload/entity-with-image'
            upload_destination: '%kernel.project_dir%/public/upload/entity-with-image'
        entity_with_media_and_image:
            uri_prefix: '/upload/entity-with-media-and-image'
            upload_destination: '%kernel.project_dir%/public/upload/entity-with-media-and-image'
